language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install python-coveralls
  - pip install coverage
before_script: flake8 .
script:
  - python setup.py develop
  - nosetests -v --with-coverage
after_success: coveralls
